### ISSUE TITLE
"cannot delete non-empty directory" with rsync syncing

### ISSUE THREAD

**Issue by kinosang** [tuna/tunasync#69]
When folders were removed on server-side, rsync refused to delete them.

See https://serverfault.com/questions/573392/rsync-cannot-delete-non-empty-directory-errors-even-with-force-option for it.

**Comment by z4yx** [comment]
`--delete-excluded` can be added to mirror config now.

```toml
[[mirrors]]
provider = "rsync"
rsync_options = [ "--delete-excluded" ]
# ...
```
